# Service: Load balancer cho Frontend pods
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: microservices
  labels:
    app: frontend
spec:
  type: LoadBalancer  # Cho phép access từ bên ngoài
  ports:
  - port: 3000
    targetPort: 80
    name: http
  selector:
    app: frontend  # Route traffic đến pods có label này