# Service: Load balancer cho Order Service pods
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: microservices
  labels:
    app: order-service
spec:
  type: ClusterIP  # Chỉ access nội bộ cluster
  ports:
  - port: 3002
    targetPort: 3002
    name: http
  selector:
    app: order-service  # Route traffic đến pods có label này